#!/bin/sh

echo "Running pre-commit hook..."

py -m pip install ruff
py -m ruff check .
py -m ruff format . 

if [ $? -ne 0 ]; then
    echo "Code formatting failed. Please fix the issues before committing."
    exit 1
fi

echo "Code formatting passed. Proceeding with commit."
exit 0