#!/bin/sh

echo "Running pre-commit hook..."

py -m pip install ruff
py -m ruff format . --check

if [ $? -ne 0 ]; then
    echo "❌ Formatting failed. Please fix the issues before committing."
    exit 1
fi

echo "✅ Formatting passed."
exit 0
